# Introduction {#intro}

[More information about our research]

[To come: recommended reading list]

## How we meet

Currently, we meet as a group in-person and on zoom on Thursday mornings, from 9-10:30. Students and postdocs also meet 1:1 in person or on Zoom with their advisor, typically on a weekly basis. 
We use Googledocs to set agendas, record decisions made, and outline action items during meetings. 
Each lab member has their own google doc for their 1:1 meetings. 
Prior to each meeting, create your agenda for that meeting there.  

## How we give feedback

Feedback, both giving and receiving it, is an important aspect of our lab. We expect feedback to be supportive but constructive. 

This [resource from UBC](https://scwrl.ubc.ca/student-resources/learning-strategies-for-communicating-science/how-to-give-and-receive-effective-feedback/) does a really great job of outlining the main points of how to give and receive feedback. 

## How we share things, internally and with the rest of the world

It is useful to have standard ways of sharing things. These don't always have to be followed but are a useful guide and will make things easier. When sending material to someone, always make sure to describe what you are sending and try to make it as easy as possible for them to help you.  

Taking a project-based approach to organizing your work makes it easier to share and solicit feedback from others, as things tend to be self-contained. Try to keep only 1 working instance of material, and use some form of version control to facilitate this (see recommendations in [Good enough practices in scientific computing
, by Wilson et al.](https://doi.org/10.1371/journal.pcbi.1005510)).

Project management tools in Github are a good way to record and document questions on analyses. Use 'Issues' on github repositories for project-related tasks and problems. Alternatively, make use of a GoogleDoc for each project to record this history, much like you would a lab notebook.  

Code: can be shared via Github repositories, or via a dedicated Google Drive folder. For specific questions on problems, please try to create a minimal reproducible example. Ensure that others can run and interact with the material being shared.  

Writing: Preferably via GoogleDoc, R Markdown, or Overleaf, but MS Word documents can also be shared. Google docs are particularly useful for collaborative writing, and have the advantage of there only ever being one version (as opposed to files that are sent around via email). Word documents should always have your last name as the first part of the file name (e.g. please no "mythesis.doc").  

Ideas: We have an NAU-Paleoclimate Slack that we use extensively, for group, small group, and 1:1 communication. It's a community-driven resource, however, the messages and files shared that way are not permanent, so keep copies. 

NPM: I like this idea, should adopt? *We maintain a lab Google Drive folder for lab publications, presentations, photos, CVs, etc. Please make use of these so that others in the lab can make fair use of our work.*

NPM: Some more ideas here: 
## Shared lab resources 
Where to find shared resources:
- Google Drive - You will be given access to the shared drive during onboarding, take a look at the Lab Meetings folder to find Lab Meeting Notes for each semester
- GitHub - nau-paleoclimate is the shared GitHub account for the lab
- lab-manual - This repository contains the lab manual, see section \ref{#nau-resources} for other useful resources
- Lab meeting schedule
- Website - Should we make a lab website?

