# Expectations {#expectations}

In addition to agreeing to follow our communities codes of conduct and the university academic integrity policy, we expect everyone in the group to echo our lab culture (Chapter \@ref(culture)). 

[NPM: is this something we should do?]

__Individual mentoring plans:__  We will work with each of you to develop your individual mentoring plan that serves to ensure your time in the group progresses your short, medium, and long-term goals. This is a useful planning document that assists in aligning expectations. Graduate students will revisit the mentoring plan during an individual meeting with Gavin at the beginning of each semester & the start of summer. Other lab members will revisit these at appropriate time scales (e.g. every 6 months).  
A template for these, with thanks to [`@duffy_ma`](https://twitter.com/duffy_ma) can be found [here](https://docs.google.com/document/d/1ie3nc6iqW5cWit_MV8BUIVmREbvUZ8b0P9dR8CGgleQ/edit?usp=sharing).

In addition, it is useful to have broad (for all lab members) and specific (i.e., grad students, research staff, etc.) expectations of our roles clarified. These are outlined below.  

## Working hours

We generally do not hold people to working a fixed schedule, or to be in the office for a certain schedule. As adults, we should all set the working schedule that is the right fit for us, and it is likely that what this 'fit' is will change over the course of the time you are in the lab. Depending on the nature of your appointment, there may be specific hours that will need to be worked and you should work with your main collaborator to outline these.  
Nick generally does not work evenings or on weekends, and does not expect that people in the lab are available at these times. Lab members should also not expect others to be available during these times.   

Graduate students are generally funded on graduate assistantships, either teaching (TA) or research (RA) assistantships. Most (but not all) students have a mix of RA and TAships over the course of their degrees. TAships are intended to average 20 hrs per week (for all activities) during the semester. It's not uncommon for the actual commitment to be less than this, but if your TA duties are consistently occupying you for more than 20 hours a week, you should discuss this with your advisor. The RA contracts state that this stipend is for 20 hrs of work per week during the semester. Most usually, students on RAships are being paid from a research grant where the focus of the grant is the topic the student is working on for their thesis research, so there is overlap here. Some people find that counting 'billable hours' is productive for them as it helps them keep accountable to themselves. Others do not find this method useful. Regularly assess what works best for you.  

Full time is enough, and we do not expect team members to work nights and weekends, though do not enforce a particular working hours schedule because students should feel flexible enough to create a work schedule that works for them. Lab members should not expect others to be available during evenings and weekends. There is value to interacting with others as part of your work, and we do expect you will be available during normal working hours for at least some of the time during the week. We also recognize that there will occasionally be times where there is a need to work more to meet a deadline, but this should be the exception - an expectation of overwork is not to be normalized.  


## Email

In the group, we communicate via email and slack. You should therefore check and respond to important emails, and check in on slack at least once a day during the normal work week. We also make use of Google Docs to hold conversations regarding research tasks. Note that being available does not mean that you are available 24/7 - this is not expected. Do not expect responses to emails after regular business hours on weekdays, or on weekends. However, because we recognize that lab members should be able to create a working schedule that is right for them, lab members should not be penalized for sending communication during these times.   


## Attendance at regularly scheduled events

Attendance is expected at:
* Departmental seminars  
* Weekly lab meetings
* Individual meetings with your advisor(s) to discuss and work on your research  
* Relevant thesis and dissertation defenses  

## Outreach

We share our learning and time with others beyond our group, knowing that this builds community and ultimately improves both the quality and impact of our science. This doesn’t mean individuals do everything, however. Group members often take on leadership roles within the university, are supportive of others in our community during their milestones, actively participate in community and university events, and perform outreach. Ask others in the group about activities they are part of, and work with Gavin when crafting your mentoring plan to identify outreach strategy that meshes well with your goals.  


## Expectations for the PI

Your advisor (as PI) will (at a minimum) provide:  
* Technical support for analysis (e.g., access to computing, training on techniques)  
* Positive feedback & constructive criticism on work  
* Professional career support  
* Support for non-technical aspects of making career progress  
* Regular meetings (at least every two weeks) to discuss work & maintain progress on goals  
* Provide clear and honest appraisal of your funding situation  

##  Graduate students

You are responsible for your degree. This means you need to stay on top of program and university deadlines, requirements, etc. [npm: this needs to be connected to NAU stuff]. See Chapter \@ref(umassd-resources) & Chapter \@ref(smast-resources) for links to resources.   

Before registering for each semester, you are required to meet with your advisor to review your course progression and discuss plans for the forthcoming semester (classes, activities, etc.).  

Course of study: Work with your advisor when crafting and revisiting your individual mentoring plans to identify classes that you will take during your academic program. 

We schedule regular individual meetings with Gavin throughout the year. At a minimum during the semester these will take place every two weeks, although weekly is more common. Meetings are a chance for you to get focused time with your advisor(s) to discuss and work on your research. Thus they are your time, so come with an agenda with a list of things that you want to accomplish and work on during that time.   

We share our research at local, national, and international meetings, and publish our findings in the scientific literature. Your advisor(s) strives to provide financial support for grad students to attend at least one major conference during their program (for MS students), or once per year for PhD students. You should expect to give a presentation (a poster or a talk) on your work at these.  

### Funding {#exp-funding}

Almost always, we only accept students if we're able to guarantee at least 4 semesters of funding for MS students, and 8 semesters of funding for PhD students. This is typically a combination of grant (RA) and teaching (TA) assistantships Students are encouraged to seek and apply for extramural funding to support their work. This includes scholarships and fellowships to pay for salary, but also smaller grants for travel, workshop attendance, or research costs. There are many opportunities out there, particularly for students. Some resources are outlined in Chapter \@ref(funding).  


## Undergraduate students

You will most likely be working with one of the lab’s research team as your primary research supervisor. The grad student or postdoc you are working with on your project will be your primary source of contact and you should work with them to establish and define your work schedule, protocols for your work, and to ensure you have the necessary equipment to perform your work tasks.  

Although the grad student / postdoc is your primary contact, always feel like you can reach out to both [Nick](mailto:nick@nau.edu) and [Darrell](mailto:darrell.kaufman@nau.edu) as the senior group leaders. We are excited to help you use your position in the lab to further your career goals and want to work with you to help you achieve them.  

If you are an hourly worker (either federal work study or grant supported) then it is critical that you complete your timesheets through Louie with your hours worked, so that you can get paid. Please submit your electronic timesheet each week by noon on Friday, to allow time for your supervisor to approve. Alert your research supervisor AND Nick or Darrell as soon as possible if there are any complications with regard to pay. We want you to be compensated for your work in a timely fashion.  


## Postdoctoral researchers

Postdocs are independent researchers and likely will likely have significant collaboration with researchers at other institutions as part of their research and position. 

In general, postdocs are expected to:  
* Be present and involved in lab meetings, workshops, campus seminars, and conferences.  
* Provide mentorship, technical support, and assistance to other lab members  
* Communicate both successes and sticking points on a regular basis with the PI  
* Work independently and collaboratively  
* Participate in professional development opportunities  
* Lead and assist in designated research projects  
* Develop and submit proposals to fund future research  

As a postdoc, a major part of your job is to look for your next job. While a postdoctoral position is a scientific research position, it is also a training opportunity and a step to something else, and a full-time permanent position beats a postdoc. Do not feel bad or awkward about pursuing (and taking) employment opportunities, and also training opportunities that help you move toward that next step. We want you to succeed!  

Postdocs will likely have active roles on advisory working groups or other professional service roles. If opportunities are not immediately apparent through your funded research, then your advisor can help strategize about where is a useful space to target your involvement.    

## Research staff

Much like post-docs, research staff operate as independent and collaborative researchers on assigned projects. As these positions are often working directly alongside your mentor/direct collaborator on particular lab projects, meetings may be more frequent than those with others in the lab. Weekly meetings should have clear agendas, and can often be used as collaborative working time to make progress on specific tasks. 

In general, staff are expected to:

* Be present and involved in lab meetings, workshops, campus seminars, and conferences  
* Provide technical support and assistance to other lab members
* Communicate both successes and sticking points on a regular basis with PI
* Work independently and collaboratively
* Lead and assist in designated research projects
* Participate in professional development opportunities (i.e., workshops, conferences, submitting previous position manuscripts [without detracting from new position])
* Seek and pursue new funding opportunities when appropriate (this will likely be dependent on your timeline)
* Produce expected output from assigned grants
* Be flexible! Additional projects may be assigned to give additional funding for your position  
* Serve as a role model and go-to resource for other members of the lab

Research staff positions may be somewhat flexible in scope. For example, the position may include some lab management, leadership, and communication responsibilities. Exact set of responsibilities and duties will be clearly defined in your position description and expectations agreed on in your work plan.  


