# Funding {#funding}

We typically do no accept students into the lab without being able to guarantee full funding (2 years for MS students, 4 years for PhD).  

Position openings in the lab will be posted through the lab website, twitter account, and via other distribution feeds (e.g. listsrvs).  

We encourage all students to apply for external funding through graduate scholarships. Some relevant ones include ...

Here is a living document of recurring funding opporunities [NPM: we need one of these] [Google Doc](https://docs.google.com/spreadsheets/d/1YGtSWJj2socIGtHLbBpHmJ7rPeDiECsdjgIz8FxUYMA/edit?ts=5e289f99#gid=0). We not only encourage students to obtain additional funding, but also staff and post-docs. And for all to apply for travel grants when attending conferences, where applicable. 

This resource is updated fairly regularly, and largely contains resources to fund yourself/research. It includes the opportunity name, institution, link, grad/undergrad/postdoc/all/early career/etc designation, the deadline, and important notes. 

We will also share funding opportunities as they come up, either to the group or in individual meetings.  

